#!/bin/sh

# uci set luci.main.lang=zh_cn
# uci set luci.main.mediaurlbase=/luci-static/argon
# uci commit luci

# @wifi-iface[0] 表示2.4G网络；@wifi-iface[1] 表示5G网络
# uci set wireless.@wifi-iface[0].ssid='OperWrt'
uci set wireless.@wifi-iface[0].encryption='WPAPSKWPA2PSK'
uci set wireless.@wifi-iface[0].key='password'
# uci set wireless.@wifi-iface[1].ssid='OperWrt'
uci set wireless.@wifi-iface[1].encryption='WPAPSKWPA2PSK'
uci set wireless.@wifi-iface[1].key='password'
uci commit wireless

sed -i 's/root:.*/root:$1$PgqmDetr$xqXbP57ysPKh9m36oycQS\/:18361:0:99999:7:::/g' /etc/shadow

# uci set wireless.encryption="WPA/WPA2"
# uci set wireless.key="password"
# uci commit wireless

uci set shadowsocksr.@global[0].pdnsd_enable='0'
uci del shadowsocksr.@global[0].tunnel_forward
uci add_list shadowsocksr.@access_control[0].wan_fw_ips='1.1.1.1'
uci add_list shadowsocksr.@access_control[0].wan_fw_ips='208.67.222.222'
uci add_list shadowsocksr.@access_control[0].wan_fw_ips='8.8.8.8'
uci add_list shadowsocksr.@access_control[0].wan_fw_ips='8.8.4.4'
uci add_list shadowsocksr.@access_control[0].wan_fw_ips='9.9.9.9'
uci add_list shadowsocksr.@access_control[0].wan_fw_ips='218.102.23.228'
uci add_list shadowsocksr.@access_control[0].wan_fw_ips='210.0.255.250'
uci add_list shadowsocksr.@access_control[0].wan_fw_ips='168.95.1.1'
uci add_list shadowsocksr.@access_control[0].wan_fw_ips='202.86.191.50'
uci add_list shadowsocksr.@access_control[0].wan_fw_ips='77.88.8.8'
uci add_list shadowsocksr.@access_control[0].wan_fw_ips='101.101.101.101'
uci add_list shadowsocksr.@access_control[0].wan_fw_ips='203.198.7.66'
uci add_list shadowsocksr.@access_control[0].wan_fw_ips='202.56.128.30'
uci add_list shadowsocksr.@access_control[0].wan_fw_ips='149.112.112.112'
uci commit shadowsocksr




exit 0
